### ISSUE TITLE
[Feature Request] provide API for accessing original images of artwork with artwork ID

### ISSUE THREAD

**Issue by seriaati** [HazelTheWitch/phixiv#1]

**Comment by HazelTheWitch** [comment]
As in a link that goes directly to an image? For example `www.phixiv.net/en/artworks/<whatever>/raw` redirects you to the proxy? I think that is doable. It would not be any cheaper than the full embed really, which is a shame, but it could be done. Is that what you mean?

If you mean an actual API, to be used from code, it would be easier to copy what is being done in `Artwork::app_request` of artwork.rs.

**Comment by seriaati** [comment]
> For example www.phixiv.net/en/artworks/<whatever>/raw redirects you to the proxy?

Yep.

> If you mean an actual API, to be used from code, it would be easier to copy what is being done in Artwork::app_request of artwork.rs.  

I just want to make a button under your embed that downloads the full image.

> I think that is doable.

Thank you!

**Comment by HazelTheWitch** [comment]
Okay, direct image links are in the form `/d/:id` and `/d/:id/:image_index` for albums. Let me know if you have any issues with it.

**Comment by seriaati** [comment]
is it like `phixiv.net/d/103234224` ? it's not working for me.

**Comment by seriaati** [comment]
nvm, working now, thank you for adding this feature.
