### ISSUE TITLE
phixiv links don't embed

### ISSUE THREAD

**Issue by 42chompii** [HazelTheWitch/phixiv#12]
Title says it all, the phixiv links I send don't work and when clicking the link the following website shows up:
![image](https://github.com/HazelTheWitch/phixiv/assets/109488630/83c28dfc-010b-4913-a318-a6274cbe12e5)

**Comment by HazelTheWitch** [comment]
Seems to have been an issue with the host, right now things are working as of 37 minutes ago.

**Comment by 42chompii** [comment]
Yup, it works again now, I'll keep that in mind next time I'm experiencing issues. Thanks for making this btw, really useful!
