### ISSUE TITLE
Request: member_illust.php embed

### ISSUE THREAD

**Issue by AEtherPi** [HazelTheWitch/phixiv#13]
![Screenshot_2023-10-01-01-09-29-13_572064f74bd5f9fa804b05334aa4f912](https://github.com/HazelTheWitch/phixiv/assets/59917665/2439013e-675f-4d20-a183-8fbfde37f811)

**Comment by HazelTheWitch** [comment]
Should be working now, easy little fix, but hop wanted to be a pain.
