### ISSUE TITLE
API and embed fixer seem to be incredibly slow after the rewrite.

### ISSUE THREAD

**Issue by seriaati** [HazelTheWitch/phixiv#15]
Artwork info API is taking 6 seconds, image proxy urls are not loading in discord, embeds are also not loading.

**Comment by HazelTheWitch** [comment]
Interesting, it was doing fine a few hours ago, I rolled back and will look into it.

**Comment by seriaati** [comment]
That was some quick response, thanks.

**Comment by seriaati** [comment]
The api response time has been reduced to 955ms.

**Comment by HazelTheWitch** [comment]
It looks like it was reauthorizing before every request, that explains why it only broke after a bit.

**Comment by HazelTheWitch** [comment]
I made the change and redeployed, I'll keep an eye on it. Thank you.
