### ISSUE TITLE
DNS: phixiv.net broken; www.phixiv.net working?

### ISSUE THREAD

**Issue by SoftwareGuy** [HazelTheWitch/phixiv#16]
Hi there!

There seems to be some weird DNS issue, where if you put something like `https://phixiv.net/en/artworks/<some id>` then it says the DNS Name could not be resolved. However, when adding the `www.` part before the `phixiv.net` part of the domain, it works as expected.

Is this intentional or an oversight?

**Comment by HazelTheWitch** [comment]
It's not really either, I used to use AWS DNS which doesn't allow for top level CNAME records, so I just didn't because it didn't really matter anyway, but I use Cloudflare now so I can set that up. Most people edit a copied link however, so it hasn't been an issue.

**Comment by SoftwareGuy** [comment]
Ah, no worries. Some contacts of mine do send me pixiv (dot net) links that don't have the `www.` part and when I found that doesn't work I manually added `www.` into the domain part to remedy it.

Thanks for the explanation!
