### ISSUE TITLE
Telegram embed issue

### ISSUE THREAD

**Issue by salvo91able** [HazelTheWitch/phixiv#17]
Telegram won't embed any post with the phixiv or ppxiv link

**Comment by HazelTheWitch** [comment]
Can you be more specific, provide screenshots if possible. Does it embed like a usual pixiv link? I don't use telegram so I need more information.

**Comment by salvo91able** [comment]
Hi, yes I can provide screenshots
![image](https://github.com/HazelTheWitch/phixiv/assets/84201239/0a6e035d-aea5-44ba-985f-a73ad7c060b4)
This is how they usually embedded up until yesterday

**Comment by salvo91able** [comment]
now they just result in link with no embedded media
![image](https://github.com/HazelTheWitch/phixiv/assets/84201239/21978e25-a83e-43b8-b6b0-ba9ce0305129)

**Comment by HazelTheWitch** [comment]
> This is how they usually embedded up until yesterday

Looking through request logs, Telegram is doing something weird with it and I'm not sure. I'm getting a request to `/en/artworks/77789607` then `/en/artworks/'https://www.pixiv.net/en/artworks/77789607'`. I made no changes, so for now I'm putting this down to a Telegram issue.

I apologize but at the moment I don't think there's much I can do, unless I'm missing something.

**Comment by HazelTheWitch** [comment]
Looks like I spoke too soon, kinda. Telegram seems to be incorrectly following a redirect. I switched it to a js redirect and it seems to work.
