### ISSUE TITLE
gif embeds not working properly

### ISSUE THREAD

**Issue by infernalsaber** [HazelTheWitch/phixiv#18]
For the images where the master image is a gif, the embed image on discord is a static jpg

Example noted:
https://www.pixiv.net/en/artworks/113020016

And the result: https://www.phixiv.net/i/c/600x1200_90/img-master/img/2023/10/31/21/42/21/113020016_master1200.jpg

**Comment by HazelTheWitch** [comment]
The issue with animated artworks is they aren't technically GIFs. They are a format called ugoria, which is a sequence of PNG or JPEG images stitched together. So with regular artworks I can just proxy the request, with ugoria one request for the GIF (or APNG or whatever I end up using as the animated format) turns into many proxied requests + stitching it together into a GIF. This isn't impossible but I am not sure how it would affect hosting costs and performance.

I'm not entirely against it but I would probably need to set up a secondary service like a cf worker to stitch and cache the stitched GIF.

**Comment by infernalsaber** [comment]
I see, thanks for the explanation. 
I won't be able to offer meaningful suggestions here owing to lack of experience, so apologies.

Although considering that pixiv caps the size of the ugoria files at 30MB, it might not be entirely implausible to consider implementing it sometime in the future.

**Comment by Lexsah** [comment]
What about using a project that already exists to do that like https://github.com/jmb6/ugoira-convert (I never tried it so I don't know if it works fine) or one of the other project related to ugoira out there ?

**Comment by HazelTheWitch** [comment]
Please make an issue here https://github.com/thelaao/phixiv
