### ISSUE TITLE
Embeds show only the first image from the posts with multiple pics

### ISSUE THREAD

**Issue by SkywalkerFox** [HazelTheWitch/phixiv#19]
It would've been nice to see few pics in the attachment when a user is trying to embed a pixiv link that contains not only 1 image. Now it works in the way that we will see only the first pic from the pixiv post.

From the technical point I understand that sometimes there might be too many images in the post to embed, but what if we limit it to 10, for example? or showing them in a few different blocks in parts?

**Comment by HazelTheWitch** [comment]
Discord does not currently have the ability to embed multiple images in one embed from a website and I feel that stitching together images will provide a worse user experience in general.

If you'd like to embed other images in a post you can add `/<index>` to the end of the url.
