### ISSUE TITLE
Change default embedded image to the "master1200" or add a syntax option to choose between full size or master1200

### ISSUE THREAD

**Issue by UmbraVivens** [HazelTheWitch/phixiv#9]
a lot of the time, art embedded goes up to 3k-4k dimensions, resulting in big image file size and affecting bandwidth/phone data, it would be great if embedding defaulted to use the master1200 copy from the post or add a syntax option to choose between it or full size. thank you

**Comment by HazelTheWitch** [comment]
The issue if I remember correctly is the API endpoint for getting images past the first does not return anything except the full size image. I may be remembering wrong, but I considered this. Could you point me to an endpoint which gives all the image URLs in that size?

The current endpoint I use is `https://app-api.pixiv.net/v1/illust/detail?illust_id={id}`.

**Comment by FichteFoll** [comment]
Referencing [some code I wrote a couple years ago](https://github.com/Infiziert90/Tsuzuru-Bot/blob/adf81b17d85ecc9a12c5ad0553bf75431636ac3c/modules/pixiv.py#L75), there appears to be a field named `illust.image_urls.large` (JSON path). I don't know whether that still works, though, and don't have a ready-to-use auth token available currently.

**Comment by HazelTheWitch** [comment]
Digging through the API a bit, looks like there is `illust.image_urls.large` for the large size and `illust.meta_single_page.original_image_url` for original when it is a single image, and `illust.meta_pages[n].image_urls` has `large` and `original` when it is a group of images.

All of this is currently being deserialized from the response already. The only real worry I have is I looked into this before and found some issue, but I can't remember what it was anymore.

What syntax do you suggest for specifying size and which size should be the default?

I am not sure when I'll get to implementing this, if someone wants to make a PR that would be greatly appreciated. If you do, `AppReponse` has all of these being deserialized already so you don't need to worry about that. This is [the relevant lines regarding image URL selection](https://github.com/HazelTheWitch/phixiv/blob/43778032d00c1e749a181acf624e2892e1d0e853/src/pixiv/artwork.rs#L173). Finally however you implement the syntax will have to be changed in [this file, which handles embed routing and processing](https://github.com/HazelTheWitch/phixiv/blob/43778032d00c1e749a181acf624e2892e1d0e853/src/phixiv.rs).

**Comment by UmbraVivens** [comment]
I'd change the default to the Master1200 image, since embeds don't never go up to the thousands of pixels, in fact i use phixiv mainly because the "official" embeds are bad (they're always just the top half of the image for some reason), but it's also kinda overkill that it fetches the full resolution of the post. if someone posts a phixiv link, and i like the art from the smaller embed, i can just open the link to access the true resolution and drop a bookmark or follow.
Lastly, to embed the full resolution i'd add `:full` as the option at the end of links, similar to `:index`.
And there's no rush, it's not such a critical thing to add, i thought it'd make things a bit smoother for everyone
